language: php
php:
    - '7.2'
    - '7.3'
    - nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyse

matrix:
    allow_failures:
        - php: nightly
