name: Check Codestyle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fix-style:
    name: Fix Code Style
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.x
        coverage: none
        tools: composer, cs2pr

    - name: Install dependencies
      run: |
        composer update --prefer-dist --no-suggest --no-progress --no-interaction

    - name: Check Code Style
      run: vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml

    - name: Show PHPCS results in PR
      run: cs2pr ./phpcs-report.xml
