name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
  - cron: '0 0 * * *'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [8.0, 7.4, 7.3]
        dependency-version: [prefer-lowest, prefer-stable]
        experimental: [false]

        include:
          - php: '8.1'
            dependency-version: 'prefer-stable'
            experimental: true

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        tools: composer

    - name: Install dependencies - normal
      if: ${{ matrix.php < 8.1 }}
      run: |
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress

    - name: Install dependencies - ignore platform reqs
      if: ${{ matrix.php >= 8.1 }}
      run: |
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress --ignore-platform-reqs

    - name: Execute Unit Tests
      run: vendor/bin/phpunit
